# Generated by Django 2.2.7 on 2021-05-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210505_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upvote_id',
            new_name='upvote_amount',
        ),
        migrations.RemoveField(
            model_name='post',
            name='link',
        ),
        migrations.AddField(
            model_name='post',
            name='Ссылка',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
