# Generated by Django 2.2.7 on 2021-05-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_post_upvote_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Ссылка',
            new_name='link',
        ),
    ]
